version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: ts-loader
    versions:
    - 8.0.2
    - 9.0.0
    - 9.1.0
  - dependency-name: "@graphql-codegen/typescript-react-apollo"
    versions:
    - 2.2.1
    - 2.2.2
    - 2.2.3
  - dependency-name: typescript
    versions:
    - 4.1.3
    - 4.1.5
    - 4.2.2
    - 4.2.3
  - dependency-name: react-scripts
    versions:
    - 4.0.1
    - 4.0.2
  - dependency-name: "@capacitor/cli"
    versions:
    - 2.4.6
  - dependency-name: class-transformer
    versions:
    - 0.3.1
